import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import TanstackQueryProvider from "@/components/providers/tanstack-query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <TanstackQueryProvider>{children}</TanstackQueryProvider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
